-- The warehouse in three layers. Bronze logs every page read (the pages themselves stay on disk under
-- data/raw/<source>/<run_week>/). Silver holds the checked rows: listings, the asking price of each
-- listing in each run week (append-only), the rejected rows with their reason and the counts of every
-- run. Gold is a star rebuilt per run week for the report and Power BI. Prices are in EGP.
-- Safe to run again: load_silver runs it at the start of every weekly run. No contact data in any table;
-- the raw pages on disk (gitignored) can hold sellers' contact details.

CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

-- Bronze ----------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bronze.fetch_log (
    source      text NOT NULL,
    run_week    date NOT NULL,                -- the Sunday the run's week starts
    url         text NOT NULL,                -- the address asked for
    final_url   text,                         -- where the site answered from, after redirects
    fetched_at  timestamptz NOT NULL,
    http_status integer,
    bytes       integer,
    path        text,                         -- the saved file, relative to data/raw/<source>/<run_week>/
    PRIMARY KEY (source, run_week, url, fetched_at)
);
COMMENT ON TABLE bronze.fetch_log IS 'One row per page read: loaded from each bronze folder''s index.csv or summary.csv.';

-- Silver ----------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS silver.area (
    area_id           text PRIMARY KEY,       -- e.g. 'new-cairo'
    name              text NOT NULL,
    lat               numeric,
    lon               numeric,
    coordinate_source text                    -- where lat and lon were taken from
);
COMMENT ON TABLE silver.area IS 'One row per area we read (data/areas.csv).';

CREATE TABLE IF NOT EXISTS silver.our_unit (
    unit_code    text PRIMARY KEY,
    area_id      text NOT NULL REFERENCES silver.area,
    compound     text NOT NULL,               -- a compound name as a listing site writes it
    developer    text,
    unit_type    text NOT NULL,
    bedrooms     integer NOT NULL,
    size_m2      numeric NOT NULL CHECK (size_m2 > 0),
    asking_price numeric NOT NULL CHECK (asking_price > 0),
    price_per_m2 numeric GENERATED ALWAYS AS (round(asking_price / size_m2, 2)) STORED
);
COMMENT ON TABLE silver.our_unit IS 'One row per unit of the client''s for sale (data/our_units.csv, generated by make_units.py).';

CREATE TABLE IF NOT EXISTS silver.listing (
    source          text NOT NULL,
    listing_id      text NOT NULL,            -- the site's own id
    url             text,
    area_id         text NOT NULL REFERENCES silver.area,
    compound        text,
    developer       text,
    unit_type       text NOT NULL,
    bedrooms        integer,
    bathrooms       integer,
    size_m2         numeric NOT NULL CHECK (size_m2 > 0),
    listed_on       date,                     -- the listing day in Cairo, when the site gives one
    first_seen_week date NOT NULL,
    last_seen_week  date NOT NULL,
    PRIMARY KEY (source, listing_id)
);
COMMENT ON TABLE silver.listing IS 'One row per site and listing: its latest description; first and last run week it was seen.';

CREATE TABLE IF NOT EXISTS silver.price_observation (
    source       text NOT NULL,
    listing_id   text NOT NULL,
    run_week     date NOT NULL,
    asking_price numeric NOT NULL CHECK (asking_price > 0),
    size_m2      numeric NOT NULL CHECK (size_m2 > 0),
    price_per_m2 numeric GENERATED ALWAYS AS (round(asking_price / size_m2, 2)) STORED,
    fetched_at   timestamptz NOT NULL,        -- when the page holding the price was read
    PRIMARY KEY (source, listing_id, run_week),
    FOREIGN KEY (source, listing_id) REFERENCES silver.listing
);
COMMENT ON TABLE silver.price_observation IS 'One row per site, listing and run week: the asking price seen. Append-only, never updated.';

CREATE TABLE IF NOT EXISTS silver.quarantine (
    id       bigserial PRIMARY KEY,
    run_week date NOT NULL,
    source   text NOT NULL,
    url      text NOT NULL,
    reason   text NOT NULL,
    payload  jsonb NOT NULL,                  -- the row as parsed, in the common shape (no contact fields)
    UNIQUE (run_week, source, url, reason)
);
COMMENT ON TABLE silver.quarantine IS 'One row per rejected row and reason in a run week; a rerun adds nothing.';

CREATE TABLE IF NOT EXISTS silver.run_log (
    source           text NOT NULL,
    area_id          text NOT NULL,           -- the area asked for (a row's own area may differ)
    run_week         date NOT NULL,
    pages_read       integer NOT NULL,
    pages_used       text[] NOT NULL,         -- the saved files the counts come from, in data/raw/<source>/<run_week>/
    stated_total     bigint,                  -- what the site says its searches hold
    rows_parsed      integer NOT NULL,
    rows_skipped     integer NOT NULL,        -- not residential, or outside our six areas
    rows_duplicate   integer NOT NULL,        -- the same listing already read this run
    rows_saved       integer NOT NULL,
    rows_quarantined integer NOT NULL,
    PRIMARY KEY (source, area_id, run_week),
    CHECK (rows_parsed = rows_skipped + rows_duplicate + rows_saved + rows_quarantined)
);
COMMENT ON TABLE silver.run_log IS 'One row per site, area and run week: the counts of the load, reconciled.';

-- Gold: a star, dimensions upserted on their natural keys so surrogate keys stay stable ----------

CREATE TABLE IF NOT EXISTS gold.dim_site (
    site_key integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source   text NOT NULL UNIQUE,
    name     text NOT NULL,
    base_url text NOT NULL,
    read_by  text NOT NULL                    -- 'weekly DAG' or 'Omar, browser'
);
COMMENT ON TABLE gold.dim_site IS 'One row per listing site.';

CREATE TABLE IF NOT EXISTS gold.dim_area (
    area_key integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    area_id  text NOT NULL UNIQUE,
    name     text NOT NULL,
    map_name text NOT NULL,                   -- 'New Cairo, Egypt', for a map visual
    lat      numeric,
    lon      numeric
);
COMMENT ON TABLE gold.dim_area IS 'One row per area.';

CREATE TABLE IF NOT EXISTS gold.dim_compound (
    compound_key integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    area_id      text NOT NULL,
    compound     text NOT NULL,               -- 'Unknown' when the site names none
    developer    text NOT NULL,               -- 'Unknown' when the site names none
    UNIQUE (area_id, compound, developer)
);
COMMENT ON TABLE gold.dim_compound IS 'One row per area, compound and developer as the sites write them; Unknown for none.';

CREATE TABLE IF NOT EXISTS gold.dim_property_type (
    type_key  integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    unit_type text NOT NULL UNIQUE
);
COMMENT ON TABLE gold.dim_property_type IS 'One row per residential unit type.';

CREATE TABLE IF NOT EXISTS gold.dim_week (
    week_key     date PRIMARY KEY,            -- the run week: the Sunday it starts
    year         integer NOT NULL,
    month        integer NOT NULL,
    week_of_year integer NOT NULL             -- the ISO week of the Monday after the Sunday
);
COMMENT ON TABLE gold.dim_week IS 'One row per run week.';

CREATE TABLE IF NOT EXISTS gold.fact_listing_price (
    site_key     integer NOT NULL REFERENCES gold.dim_site,
    area_key     integer NOT NULL REFERENCES gold.dim_area,
    compound_key integer NOT NULL REFERENCES gold.dim_compound,
    type_key     integer NOT NULL REFERENCES gold.dim_property_type,
    week_key     date NOT NULL REFERENCES gold.dim_week,
    listing_id   text NOT NULL,               -- degenerate dimension: the site's own id
    asking_price numeric NOT NULL,
    size_m2      numeric NOT NULL,
    price_per_m2 numeric NOT NULL,
    bedrooms     integer,
    PRIMARY KEY (site_key, listing_id, week_key)
);
COMMENT ON TABLE gold.fact_listing_price IS 'One row per site, listing and run week: the asking price, size and price per m2.';

CREATE TABLE IF NOT EXISTS gold.fact_our_unit (
    unit_code    text PRIMARY KEY,
    area_key     integer NOT NULL REFERENCES gold.dim_area,
    type_key     integer NOT NULL REFERENCES gold.dim_property_type,
    compound_key integer NOT NULL REFERENCES gold.dim_compound,
    size_m2      numeric NOT NULL,
    asking_price numeric NOT NULL,
    price_per_m2 numeric NOT NULL
);
COMMENT ON TABLE gold.fact_our_unit IS 'One row per unit of the client''s.';

-- Rebuild gold for one run week: upsert the dimensions, then replace that week's fact rows and our
-- units. The caller runs it in one transaction, so a rebuild gives the same rows.
CREATE OR REPLACE FUNCTION gold.build(p_week date) RETURNS void LANGUAGE sql AS $$
INSERT INTO gold.dim_site (source, name, base_url, read_by) VALUES
    ('realestate', 'realestate.eg', 'https://realestate.eg', 'weekly DAG'),
    ('propertyfinder', 'Property Finder Egypt', 'https://www.propertyfinder.eg', 'weekly DAG'),
    ('dubizzle', 'Dubizzle Egypt', 'https://www.dubizzle.com.eg', 'weekly DAG'),
    ('nawy', 'Nawy', 'https://www.nawy.com', 'weekly DAG'),
    ('bayut', 'Bayut Egypt', 'https://www.bayut.eg', 'Omar, browser'),
    ('aqarmap', 'Aqarmap', 'https://aqarmap.com.eg', 'Omar, browser')
ON CONFLICT (source) DO UPDATE SET name = EXCLUDED.name, base_url = EXCLUDED.base_url, read_by = EXCLUDED.read_by;

INSERT INTO gold.dim_area (area_id, name, map_name, lat, lon)
SELECT area_id, name, name || ', Egypt', lat, lon FROM silver.area
ON CONFLICT (area_id) DO UPDATE SET name = EXCLUDED.name, map_name = EXCLUDED.map_name, lat = EXCLUDED.lat, lon = EXCLUDED.lon;

INSERT INTO gold.dim_compound (area_id, compound, developer)
SELECT area_id, coalesce(compound, 'Unknown'), coalesce(developer, 'Unknown') FROM silver.listing
UNION
SELECT area_id, compound, coalesce(developer, 'Unknown') FROM silver.our_unit
ON CONFLICT DO NOTHING;

INSERT INTO gold.dim_property_type (unit_type)
SELECT unit_type FROM silver.listing UNION SELECT unit_type FROM silver.our_unit
ON CONFLICT DO NOTHING;

INSERT INTO gold.dim_week (week_key, year, month, week_of_year)
VALUES (p_week, extract(year FROM p_week), extract(month FROM p_week), extract(week FROM p_week + 1))
ON CONFLICT DO NOTHING;

DELETE FROM gold.fact_listing_price WHERE week_key = p_week;

INSERT INTO gold.fact_listing_price
    (site_key, area_key, compound_key, type_key, week_key, listing_id, asking_price, size_m2, price_per_m2, bedrooms)
SELECT s.site_key, a.area_key, c.compound_key, t.type_key, o.run_week, o.listing_id,
       o.asking_price, o.size_m2, o.price_per_m2, l.bedrooms
FROM silver.price_observation o
JOIN silver.listing l USING (source, listing_id)
JOIN gold.dim_site s ON s.source = o.source
JOIN gold.dim_area a ON a.area_id = l.area_id
JOIN gold.dim_compound c ON c.area_id = l.area_id AND c.compound = coalesce(l.compound, 'Unknown')
                        AND c.developer = coalesce(l.developer, 'Unknown')
JOIN gold.dim_property_type t ON t.unit_type = l.unit_type
WHERE o.run_week = p_week;

DELETE FROM gold.fact_our_unit;

INSERT INTO gold.fact_our_unit (unit_code, area_key, type_key, compound_key, size_m2, asking_price, price_per_m2)
SELECT u.unit_code, a.area_key, t.type_key, c.compound_key, u.size_m2, u.asking_price, u.price_per_m2
FROM silver.our_unit u
JOIN gold.dim_area a ON a.area_id = u.area_id
JOIN gold.dim_property_type t ON t.unit_type = u.unit_type
JOIN gold.dim_compound c ON c.area_id = u.area_id AND c.compound = u.compound
                        AND c.developer = coalesce(u.developer, 'Unknown');
$$;
COMMENT ON FUNCTION gold.build(date) IS 'Rebuilds gold for one run week: dimensions upserted, that week''s facts and our units replaced.';

-- Gold views ------------------------------------------------------------------------------------

CREATE OR REPLACE VIEW gold.price_change AS
SELECT site_key, listing_id, area_key, compound_key, type_key, old_week_key, week_key,
       old_price_per_m2, new_price_per_m2,
       round((new_price_per_m2 - old_price_per_m2) / old_price_per_m2 * 100, 2) AS change_pct,
       new_price_per_m2 < old_price_per_m2 AS is_cut
FROM (
    SELECT f.*, f.price_per_m2 AS new_price_per_m2,
           lag(f.price_per_m2) OVER w AS old_price_per_m2,
           lag(f.week_key) OVER w AS old_week_key
    FROM gold.fact_listing_price f
    WINDOW w AS (PARTITION BY f.site_key, f.listing_id ORDER BY f.week_key)
) t
WHERE old_price_per_m2 IS NOT NULL AND new_price_per_m2 <> old_price_per_m2;
COMMENT ON VIEW gold.price_change IS 'One row per listing whose price per m2 changed from its previous run week; is_cut when it fell.';

CREATE OR REPLACE VIEW gold.pooled_listing_price AS
SELECT f.*
FROM gold.fact_listing_price f
JOIN gold.dim_site s USING (site_key)
WHERE NOT (s.source = 'bayut' AND EXISTS (
    SELECT 1 FROM gold.fact_listing_price d JOIN gold.dim_site ds USING (site_key)
    WHERE ds.source = 'dubizzle' AND d.listing_id = f.listing_id AND d.week_key = f.week_key));
COMMENT ON VIEW gold.pooled_listing_price IS 'The facts for views that pool over sites: a Bayut row whose listing_id is also a Dubizzle row that week is left out, as Bayut Egypt mirrors Dubizzle''s ads.';

CREATE OR REPLACE VIEW gold.area_benchmark AS
SELECT area_key, type_key, week_key, count(*) AS listings,
       round(percentile_cont(0.5) WITHIN GROUP (ORDER BY price_per_m2)::numeric, 2) AS median_price_per_m2,
       round(percentile_cont(0.25) WITHIN GROUP (ORDER BY price_per_m2)::numeric, 2) AS p25_price_per_m2,
       round(percentile_cont(0.75) WITHIN GROUP (ORDER BY price_per_m2)::numeric, 2) AS p75_price_per_m2
FROM gold.pooled_listing_price
WHERE week_key = (SELECT max(week_key) FROM gold.fact_listing_price)
GROUP BY area_key, type_key, week_key;
COMMENT ON VIEW gold.area_benchmark IS 'Latest run week, one row per area and unit type, pooled over sites: listings and price per m2 quartiles.';

CREATE OR REPLACE VIEW gold.area_site_benchmark AS
SELECT site_key, area_key, type_key, week_key, count(*) AS listings,
       round(percentile_cont(0.5) WITHIN GROUP (ORDER BY price_per_m2)::numeric, 2) AS median_price_per_m2,
       round(percentile_cont(0.25) WITHIN GROUP (ORDER BY price_per_m2)::numeric, 2) AS p25_price_per_m2,
       round(percentile_cont(0.75) WITHIN GROUP (ORDER BY price_per_m2)::numeric, 2) AS p75_price_per_m2
FROM gold.fact_listing_price
WHERE week_key = (SELECT max(week_key) FROM gold.fact_listing_price)
GROUP BY site_key, area_key, type_key, week_key;
COMMENT ON VIEW gold.area_site_benchmark IS 'Latest run week, one row per site, area and unit type: listings and price per m2 quartiles.';

CREATE OR REPLACE VIEW gold.unit_gap AS
SELECT u.unit_code, u.area_key, u.type_key, u.compound_key, u.price_per_m2, b.median_price_per_m2,
       round((u.price_per_m2 - b.median_price_per_m2) / b.median_price_per_m2 * 100, 2) AS gap_pct,
       count(f.listing_id) AS listings_compared,
       count(f.listing_id) FILTER (WHERE f.price_per_m2 < u.price_per_m2) AS listings_cheaper,
       round(avg((f.price_per_m2 < u.price_per_m2)::int) * 100, 2) AS pct_listings_cheaper
FROM gold.fact_our_unit u
LEFT JOIN gold.area_benchmark b USING (area_key, type_key)
LEFT JOIN gold.pooled_listing_price f ON f.area_key = u.area_key AND f.type_key = u.type_key AND f.week_key = b.week_key
GROUP BY u.unit_code, b.median_price_per_m2;
COMMENT ON VIEW gold.unit_gap IS 'One row per unit of ours against the latest week''s pooled median of its area and type; NULLs when none.';

CREATE OR REPLACE VIEW gold.area_gap AS
SELECT area_key, count(*) AS units, count(gap_pct) AS units_compared,
       round(percentile_cont(0.5) WITHIN GROUP (ORDER BY gap_pct)::numeric, 2) AS median_gap_pct,
       round(sum(listings_cheaper) * 100.0 / nullif(sum(listings_compared), 0), 2) AS pct_listings_cheaper,
       rank() OVER (ORDER BY abs(percentile_cont(0.5) WITHIN GROUP (ORDER BY gap_pct)) DESC NULLS LAST) AS gap_rank
FROM gold.unit_gap
GROUP BY area_key;
COMMENT ON VIEW gold.area_gap IS 'One row per area: the median gap of our units, the share of compared listings cheaper; rank 1 = widest gap.';
